blank_issues_enabled: false
contact_links:
  - name: Bienvenida a GitHub
    url: https://github.com/IIC2343/Syllabus/issues/1
    about: ¡Nos mudamos a GitHub!
  - name: Información de contacto
    url: https://github.com/IIC2343/Syllabus#contacto
    about: Si necesitas contactarte con nosotros, ¡escríbenos!
